# Exercise on One-Hot Encoding

## Imports

In [1]:
import importlib
import matplotlib.pyplot as plt
import numpy as np
import numpy.typing as npt
import pandas as pd

In [4]:
import sys
sys.path.append('..')

import models
import toolkit

importlib.reload(models)
importlib.reload(toolkit)

from models import *
from toolkit import *

model_kit = ModelKit()
stat_kit = StatKit()

## Exercise 1: Single Categorical Feature

### Setup

- **Goal**: Predict Price based solely on the type of Fruit.
- **Task**: 
    - One-hot encode 'Fruit',
    - drop one category,
    - train a model, and
    - interpret the intercept.

In [3]:
df1 = pd.DataFrame({
    "Fruit": ["Apple", "Apple", "Banana", "Banana", "Cherry", "Cherry"],
    "Price": [1.2, 1.3, 0.5, 0.6, 3.0, 3.2]
})
df1

    Fruit  Price
0   Apple    1.2
1   Apple    1.3
2  Banana    0.5
3  Banana    0.6
4  Cherry    3.0
5  Cherry    3.2

### Solution

In [7]:
model1 = MultiLinearRegression()

In [5]:
df1_enc = stat_kit.one_hot_encode(df1, columns="Fruit")

In [6]:
df1_enc

   Price  Fruit_Apple  Fruit_Banana  Fruit_Cherry
0    1.2          1.0           0.0           0.0
1    1.3          1.0           0.0           0.0
2    0.5          0.0           1.0           0.0
3    0.6          0.0           1.0           0.0
4    3.0          0.0           0.0           1.0
5    3.2          0.0           0.0           1.0

## Exercise 2

In [ ]:
# Exercise 2: Categorical + Continuous Feature
# Goal: Predict Salary based on Degree type and Years of Experience.
# Task: One-hot encode 'Degree'. Notice how the interpretation of the intercept changes now that 'Experience' is in the equation.
df2 = pd.DataFrame({
    "Degree": ["Bachelors", "Bachelors", "Masters", "Masters", "PhD", "PhD"],
    "Experience": [1, 3, 2, 5, 2, 6],
    "Salary": [65, 75, 80, 95, 95, 115] 
})
df2

## Exercise 3

In [ ]:
# Exercise 3: Multiple Categorical Features
# Goal: Predict Rent based on City and Property Type.
# Task: One-hot encode BOTH 'City' and 'Type'. Drop one category from each. 
# Observe what combination of features the intercept (grand baseline) represents.
df3 = pd.DataFrame({
    "City": ["London", "London", "Paris", "Paris", "NY", "NY"],
    "Type": ["Apartment", "House", "Apartment", "House", "Apartment", "House"],
    "Rent": [2000, 3000, 1800, 2800, 2500, 3500]
})
df3